#!/usr/bin/env node
// Generates js/config.js from environment variables at build time.
//
// Vercel (or any local shell) supplies SUPABASE_URL / SUPABASE_ANON_KEY as
// environment variables; this script writes them into a small generated
// module that the rest of the app imports/reads from. js/config.js is
// gitignored so the real credentials never live in tracked source.
//
// NOTE: The DEFAULT_* values below are a fallback so the app still builds and
// runs when no environment variables are configured. Environment variables
// always take precedence. Prefer setting them in Vercel (Settings →
// Environment Variables) rather than relying on these defaults — that way the
// credentials can be rotated without a code change.
'use strict';

const fs = require('fs');
const path = require('path');

// Fallback values used only when the environment variables are absent.
const DEFAULT_SUPABASE_URL = 'https://kzykuuxoivrttfdjdypl.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eWt1dXhvaXZydHRmZGpkeXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1NDQ2NTcsImV4cCI6MjEwMTEyMDY1N30.qHHVx4J626WgTxirEsPVKC8xt-T0z44VyACVQRIPl00';

// The support mailer's deployed name. Supabase's dashboard editor names a new
// function itself, and a project whose function ended up called something else
// had an app calling `support-notify` and getting a 404 on every message. This
// is the seam that fixes that without a code change — and without it, the only
// remedy is editing the app.
const SUPPORT_NOTIFY_FUNCTION = process.env.SUPPORT_NOTIFY_FUNCTION || 'support-notify';

const SUPABASE_URL = process.env.SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || DEFAULT_SUPABASE_ANON_KEY;

if (!process.env.SUPABASE_URL || !process.env.SUPABASE_ANON_KEY) {
  console.warn(
    '[generate-config] SUPABASE_URL and/or SUPABASE_ANON_KEY are not set in the ' +
    'environment — falling back to the defaults baked into this script. Set them ' +
    'in Vercel (Settings → Environment Variables) to override.'
  );
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(SUPABASE_URL)) {
  console.warn(
    `[generate-config] SUPABASE_URL ("${SUPABASE_URL}") doesn't look like a Supabase project URL ` +
    '(expected https://<project-ref>.supabase.co). Double-check your environment variable.'
  );
}

const outPath = path.join(__dirname, '..', 'js', 'config.js');

// Make sure js/ exists before writing into it.
fs.mkdirSync(path.dirname(outPath), { recursive: true });

const contents = `// AUTO-GENERATED by scripts/generate-config.js — do not edit directly.
// Regenerated on every \`npm run build\` / \`npm run dev\` from environment
// variables. See README.md for how to set SUPABASE_URL / SUPABASE_ANON_KEY.
//
// Loaded as a plain (non-module) script, so it must run before anything that
// reads window.SUPABASE_URL / window.SUPABASE_ANON_KEY.

window.SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
window.SUPPORT_NOTIFY_FUNCTION = ${JSON.stringify(SUPPORT_NOTIFY_FUNCTION)};
`;

fs.writeFileSync(outPath, contents);
console.log(`[generate-config] Wrote ${path.relative(process.cwd(), outPath)}`);
if (SUPPORT_NOTIFY_FUNCTION !== 'support-notify') {
  console.log(`[generate-config] Support mail will call the "${SUPPORT_NOTIFY_FUNCTION}" function`);
}
