#!/usr/bin/env node
// Generates js/config.js from environment variables at build time.
//
// Vercel (or any local shell) supplies SUPABASE_URL / SUPABASE_ANON_KEY as
// environment variables; this script writes them into a small generated
// module that the rest of the app imports/reads from. js/config.js is
// gitignored so the real credentials never live in tracked source.
'use strict';

const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn(
    '[generate-config] SUPABASE_URL and/or SUPABASE_ANON_KEY are not set. ' +
    'js/config.js will be generated with empty values — Supabase calls will fail until they are configured.'
  );
}

const outPath = path.join(__dirname, '..', 'js', 'config.js');

const contents = `// AUTO-GENERATED by scripts/generate-config.js — do not edit directly.
// Regenerated on every \`npm run build\` / \`npm run dev\` from environment
// variables. See README.md for how to set SUPABASE_URL / SUPABASE_ANON_KEY.
//
// Loaded as a plain (non-module) script, so it must run before anything that
// reads window.SUPABASE_URL / window.SUPABASE_ANON_KEY.

window.SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
`;

fs.writeFileSync(outPath, contents);
console.log(`[generate-config] Wrote ${path.relative(process.cwd(), outPath)}`);
